### ISSUE TITLE
Next button on subcategories does not work (Dashboard 2.0)

### ISSUE THREAD

**Issue by khalibloo** [mirumee/saleor-dashboard#72]
### What I'm trying to achieve
When more than 20 subcategories are present, only the first page is accessible. The button to go to the next page of the list is always disabled.

### Steps to reproduce the problem
1. Add more than 20 subcategories in a category
2. Try to navigate to the next page

**System information**
Operating system: Windows 10 x64
Browser: Firefox 68

**Comment by dominik-zeglen** [comment]
Must have been fixed some time ago, because it works properly now.

**Comment by khalibloo** [comment]
I just updated and tried again. The issue is still present. When I click next, a gql request is sent, but the response is always the same first 20 subcategories. I believe this is the culprit https://github.com/mirumee/saleor-dashboard/blob/2b0f2933ecbbfb801f1b3a72db4173e14cf73d18/src/categories/queries.ts#L86
It should be using the `$after` here.

**Comment by maarcingebala** [comment]
I can confirm it doesn't work, I've just tested it with about 30 subcategories- the button is inactive @dominik-zeglen.
